import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { cn } from "@/lib/utils";
import { CursorGlow } from "@/components/utils/CursorGlow";
import Navbar from "@/components/Navbar";
import Footer from "@/components/sections/Footer";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Happie Samuel",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        "font-sans",
        inter.className,
        inter.variable,
      )}
    >
      <body className="min-h-full flex flex-col">
        <CursorGlow />
        <div className="max-w-[120rem] mx-auto w-full">
          <Navbar />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
