import type { Metadata } from "next";
import { Caveat, Geist, Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { CursorGlow } from "@/components/utils/CursorGlow";
import ClientRoot from "@/components/ClientRoot";
import TransitionProvider from "@/lib/TransitionProvider";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });
const caveat = Caveat({
  subsets: ["latin"],
  variable: "--font-script",
  weight: ["700"],
});
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Happie Samuel",
  description: "Generated by create next app",
};

// export const metadata: Metadata = {
//   title: {
//     default: "Smart Farm Management System",
//     template: "%s | S.F.M.S",
//   },
//   description:
//     "A smart farm management system for monitoring crops, managing farm operations, tracking finances, and improving agricultural productivity.",
//   keywords: [
//     "Smart Farm",
//     "Agriculture",
//     "Farm Management System",
//     "Crop Monitoring",
//     "AgriTech",
//     "Nigeria Farming",
//   ],

//   metadataBase: new URL("https://smart-farm-managementt.vercel.app"),
//   openGraph: {
//     title: "Smart Farm Management System",
//     description:
//       "Monitor crops, manage farm operations, track finances, and improve agricultural productivity — all in one platform.",
//     url: "https://smart-farm-managementt.vercel.app",
//     siteName: "Smart Farm Management System",
//     images: [
//       {
//         url: "/farm-2.jpg",
//         width: 1200,
//         height: 630,
//         alt: "Smart Farm Management System - Farm Overview",
//       },
//       {
//         url: "/farm-3.jpg",
//         width: 1200,
//         height: 630,
//         alt: "Smart Farm Management System - Dashboard",
//       },
//       {
//         url: "/farm-4.jpg",
//         width: 1200,
//         height: 630,
//         alt: "Smart Farm Management System - Crop Monitoring",
//       },
//     ],
//     locale: "en_NG",
//     type: "website",
//   },
//   twitter: {
//     card: "summary_large_image",
//     title: "Smart Farm Management System",
//     description:
//       "Monitor crops, manage farm operations, track finances, and improve agricultural productivity.",
//     images: ["/farm-1.jpg"],
//   },
// };

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        "font-sans",
        inter.className,
        inter.variable,
      )}
    >
      <ClientRoot>
        <body className="min-h-full flex flex-col">
          <CursorGlow />
          <TransitionProvider>{children}</TransitionProvider>
        </body>
      </ClientRoot>
    </html>
  );
}
