import type { Metadata } from "next";
import { Caveat, Geist, Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { CursorGlow } from "@/components/utils/CursorGlow";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });
const caveat = Caveat({
  subsets: ["latin"],
  variable: "--font-script",
  weight: ["700"],
});
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Happie Samuel",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        "font-sans",
        inter.className,
        inter.variable,
      )}
    >
      <body className="min-h-full flex flex-col">
        <CursorGlow />
        {children}
      </body>
    </html>
  );
}
